### ISSUE TITLE
CirculantMatrix and NegacirculantMatrix output behavior

### ISSUE THREAD

**Issue by sujikin** [gap-packages/guava#58]
Hi,

I am observing the below behavior in latest Guava library

gap>k:=3;L:=[1,2,3];;
gap>M:=CirculHantMatrix(k,L);;
gap>Display(M);
[ [1, 2, 3],
  [2, 3, 1],
  [3, 1, 2]]

gap>M:=NegacirculantMatrix(k,L);;
gap>Display(M);
[ [1, 2, 3],
  [-3, 1, 2],
  [-2, -3, 1]]

The definition of Negacirculantmatrix is as usual but the definition of Circulant Matrix is different from standard definition.

Please elaborate on this.

Any way to get the usual circulant?

**Comment by osj1961** [comment]
I've looked into this a bit and it seems that CirculantMatrix() is a utility function created when D. Joyner was investigating Quasi-Quadratic Residue codes.  That seems to be the only place in the library where this function gets used.  Oddly, the definitions I've found for QQR codes specify the cycling of the rows to go to the right (as you noted, this is more standard).  I will fix this in the repo, since it seems very unlikely that the change will break any existing code.  It my be a while before a new release comes out so you may to just replace your copy of "util2.gi" with one from git.
